declare module 'mammoth';
declare module 'epubjs';
declare module 'heic2any';
declare module 'pdfjs-dist/legacy/build/pdf';
declare module 'pdfjs-dist/legacy/build/pdf.worker.min.mjs?raw';
declare module '@ffmpeg/core?url';
declare module '@ffmpeg/core/wasm?url';
declare module '@ffmpeg/ffmpeg/worker?raw';
declare module '@ffmpeg/ffmpeg/worker?url';
